stages:
  - train_nlu

train_nlu:
  stage: train_nlu
  image: node:18
  script:
    - nvidia-smi
    # - npm run Rasa:Generate
    # - git config --global user.name "Your Name"
    # - git config --global user.email "youremail@example.com"
    # - git add .
    # - git commit -m "Update generated model [skip ci]"
    # - git push origin main
  only:
    - main
