FROM node:18-alpine
RUN apk update && apk add git

# Set the working directory inside the container
WORKDIR /app
# Copy the source code to the container
COPY ./*.json /app
COPY ./common /app/common
COPY ./src /app/src
COPY ./client /app/client
# Install dependencies
RUN npm install


# Start the action server
CMD [ "npm", "run", "tortiseCache" ]