version: '3.8'

services:
  stt:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: ./services/stt
      dockerfile: Dockerfile.jetson
    volumes:
      - /data/voice:/data/voice
      - /data/ai-voice-cloning:/data/ai-voice-cloning
      - ~/.cache:/root/.cache/
      - ~/.ssh:/root/.ssh
    deploy:
      # mode: replicated
      # replicas: 4
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
