name: Run Rasa:Generate
on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Change this to the desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run Rasa:Generate
        run: npm run Rasa:Generate
      - name: Configure Git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "youremail@example.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update generated model [skip ci]"
          git push origin main
